### ISSUE TITLE
HotKey Funktion 

### ISSUE THREAD

**Issue by uBen-TAF** [CommonParrot/HLLMapCapture#2]
hello,
there is a problem when I want to relocate the hot key to my mouse. It will not reccon the mouse as an input or key option. Would it be possible to integrate the mouse keys as an optional hot key for this tool ?
Thank you in advace
Benji

**Comment by CommonParrot** [comment]
Hi @uBen-TAF , do you want to bind to the extra keys(side buttons/middle click) on your mouse or one of the main keys (left/right click)?
I will look into implementing this in the coming week, but it's not a good idea to use a hotkey which is often used in normal gameplay, outside of the map screen. That would lead to more delay in key presses and unnecessary performance overhead while playing. So I'm not sure if binding left/right click should be easily possible... maybe I'll include a warning for that.

**Comment by uBen-TAF** [comment]
hi, 
I really should have said it before, sorry. I mean the additional buttons on the mouse, i.e. the additional buttons on the side. The main buttons on the mouse are not used to operate the tool.

**Comment by CommonParrot** [comment]
I implemented the feature in the newest commit. The one limitation with this is that you can't assign an individual side button.
No matter what side button you press, it will trigger the map detection.

The new mouse hotkey detection method uses this: https://learn.microsoft.com/en-us/windows/win32/winmsg/lowlevelmouseproc, to get any mouse event, even when HLLMapCapture is not focused. But it only detects side/extra buttons in general not individually.

So this is more of an update until i have the real solution.

**Comment by CommonParrot** [comment]
Turns out it does detect which side button was detected and I just didn't see it.
It works now with release v1.1.3👌
